package org.fhossyl.packets

import org.fhossyl.packets.common.MetadataType

private typealias Type = MetadataType

enum class BedrockMetadata(val type: Type) {

    Flags(Type.Flags),
    Health(Type.Int),
    Variant(Type.Int),
    Color(Type.Byte),
    NameTag(Type.String),
    OwnerEid(Type.Long),
    TargetEid(Type.Long),
    Air(Type.Short),
    PotionColor(Type.Int),
    PotionAmbient(Type.Byte),
    HurtTime(Type.Int),
    JumpDuration(Type.Byte),
    HurtDirection(Type.Int),
    PaddleTimeLeft(Type.Float),
    PaddleTimeRight(Type.Float),
    ExperienceValue(Type.Int),
    DisplayItem(Type.Int),
    DisplayOffset(Type.Unknown), // Can be an integer or a long value
    HasDisplay(Type.Byte),
    Charged(Type.Byte),
    EndermanHeldItemId(Type.Int),
    EntityAge(Type.Byte),
    CanStartSleep(Type.Byte),
    PlayerIndex(Type.Int),
    BedRespawnPos(Type.Vector3I),
    FireballPowerX(Type.Float),
    FireballPowerY(Type.Float),
    FireballPowerZ(Type.Float),
    PotionAuxValue(Type.Short),
    LeadHolderEid(Type.Long),
    Scale(Type.Float),
    HasNpcComponent(Type.Byte),
    SkinId(Type.String),
    NpcSkinId(Type.String),
    UrlTag(Type.String),
    MaxAir(Type.Short),
    MarkVariant(Type.Int),
    ContainerType(Type.Byte),
    ContainerBaseSize(Type.Int),
    ContainerExtraSlotsPerStrength(Type.Int),
    BlockTarget(Type.Vector3I),
    WitherInvulnerableTicks(Type.Int),
    WitherTarget1(Type.Long),
    WitherTarget2(Type.Long),
    WitherTarget3(Type.Long),
    WitherAerialAttack(Type.Short),
    BoundingBoxWidth(Type.Float),
    BoundingBoxHeight(Type.Float),
    FuseLength(Type.Int),
    RiderSeatPosition(Type.Vector3F),
    RiderRotationLocked(Type.Byte),
    RiderMaximumRotation(Type.Float),
    RiderMinimumRotation(Type.Float),
    AreaEffectCloudRadius(Type.Float),
    AreaEffectCloudWaiting(Type.Int),
    AreaEffectCloudParticleId(Type.Int),
    ShulkerPeakHeight(Type.Int),
    ShulkerAttackFace(Type.Byte),
    ShulkerAttackPos(Type.Vector3I),
    TradingPlayerEid(Type.Long),
    CommandBlockEnabled(Type.Byte),
    CommandBlockCommand(Type.String),
    CommandBlockLastOutput(Type.String),
    CommandBlockTrackOutput(Type.Byte),
    ControllingRiderSeatNumber(Type.Byte),
    Strength(Type.Int),
    MaxStrength(Type.Int),
    EvokerSpellColor(Type.Int),
    LimitedLife(Type.Int),
    ArmorStandPoseIndex(Type.Int),
    EnderCrystalTimeOffset(Type.Int),
    AlwaysShowNameTag(Type.Byte),
    Color2(Type.Byte),
    ScoreTag(Type.String),
    BalloonAttachedEntity(Type.Long),
    PufferFishSize(Type.Byte),
    BoatBubbleTime(Type.Int),
    AgentId(Type.Long),
    EatCounter(Type.Int),
    Flags2(Type.Flags),
    AreaEffectCloudDuration(Type.Int),
    AreaEffectCloudSpawnTime(Type.Int),
    AreaEffectCloudRadiusPerTick(Type.Float),
    AreaEffectCloudChangeOnPickup(Type.Float),
    AreaEffectCloudCount(Type.Int),
    InteractiveTag(Type.String),
    TradeTier(Type.Int),
    MaxTradeTier(Type.Int),
    TradeXP(Type.Int);

}
